### ISSUE TITLE
use a flash message here

### ISSUE THREAD

**Issue by aric87** [jayzamazing/Web-Developer-Portfolio#19]
https://github.com/jayzamazing/Web-Developer-Portfolio/blob/master/js/app.js#L5

It's small, but catching the response and flashing a success/error message is a nice touch that shows that you're thinking beyond the basics.

**Comment by jayzamazing** [comment]
Decided on bootstrap alert for this for the time being. https://github.com/jayzamazing/Web-Developer-Portfolio/pull/49
